apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: color
  name: color
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
        - name: color
<<<<<<< HEAD
          image: docker.io/aperturesci/rollouts-demo:7c5d0ba
=======
          image: aperturesci/rollouts-demo:684833d
>>>>>>> a7d26a8e4051f0fb7fe877704360c1a601b3e762
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
