apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: color
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
        - name: color
<<<<<<< HEAD
          image: docker.io/aperturesci/rollouts-demo:7c5d0ba
=======
          image: aperturesci/rollouts-demo:684833d
>>>>>>> a7d26a8e4051f0fb7fe877704360c1a601b3e762
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    canary:
      canaryService: color-preview
      steps:
        - setWeight: 20
        - pause: {duration: 30}
        - setWeight: 40
        - pause: {duration: 30}
        - setWeight: 60
        - pause: {duration: 30}
        - setWeight: 80
        - pause: {duration: 30}
