# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: quay.io/codefresh-contrib/worker
  tag: stable
redis:
  usePassword: false
replicaCount: 1
