apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  # - ingress.yaml
  # - ingress-preview.yaml
  - rollout.yaml
#- deployment.yaml
#namespace: staging
images:
  - name: docker.io/aperturesci/rollouts-demo
    newTag: 0ef92c8
