result:
  image:
    repository: aperturesci/result
    tag: 738b8db
vote:
  image:
    repository: aperturesci/vote
    tag: stable
worker:
  image:
    repository: aperturesci/worker
    tag: 738b8db
