result:
  image:
    repository: aperturesci/result
    tag: stable
vote:
  image:
    repository: aperturesci/vote
    tag: stable
worker:
  image:
    repository: aperturesci/worker
    tag: stable
