apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: globex-dev
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: globex-dev.kubecon.sales-dev.codefresh.io
      http:
        paths:
          - path: /globex(/|$)(.*)
            backend:
              service:
                name: globex
                port:
                  number: 80
            pathType: Prefix
