apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: globex-dev
spec:
  ingressClassName: nginx
  rules:
    - host: globex-dev.kubecon.sales-dev.codefresh.io
      http:
        paths:
          - path: /globex
            backend:
              service:
                name: globex
                port:
                  number: 80
            pathType: Prefix
