apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubescape-scan-2
subjects:
- kind: ServiceAccount
  name: kubescape-scan
  namespace: mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubescape-scan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescape-scan
  namespace: mysql
