apiVersion: v1
kind: Namespace
metadata:
  name: kubescape
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubescape-scan
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubescape-scan
subjects:
- kind: ServiceAccount
  name: kubescape-scan
  namespace: kubescape
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubescape-scan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescape-scan
  namespace: kubescape
