apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  # - ingress.yaml
  #- ingress-preview.yaml
  - rollout.yaml
#- deployment.yaml
#namespace: qa
images:
  - name: docker.io/aperturesci/rollouts-demo
    newTag: 5f0c004
