apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - rollout.yaml
  - ingress.yaml
  - ingress-preview.yaml
  - analysis-prometheus.yaml
  - prometheus-ingress.yaml
images:
  - name: docker.io/aperturesci/rollouts-demo
    newTag: ebf7e92
