apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: color
  namespace: gitops
spec:
  generators:
    - list:
        elements:
          - cluster: kc-v-dev
            short: dev
          - cluster: kc-v-qa
            short: qa
          - cluster: kc-v-staging
            short: staging
          - cluster: kc-v-prod
            short: prod
  template:
    metadata:
      name: 'color-{{short}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '/manifests/color/aperture-{{short}}'
        codefresh.io/product: color-app
      labels:
        codefresh.io/product: color-app
    spec:
      project: default
      source:
        repoURL: https://github.com/aperture-sci/gitops_applications.git
        targetRevision: main
        path: 'manifests/color/{{short}}'
      destination:
        name: '{{cluster}}'
        namespace: '{{short}}'
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
