kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: scan
spec:
  metrics:
  - name: scan
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: kubescape
                image: kubescape-cli:3.0.1
                command: [bash, -c]
                args: [kubescape scan]
                env:
                - name: VERBOSE
                  value: on
                - name: FRAMEWORKS
                  value: MITRE
                - name: ACCOUNT
                  valueFrom:
                    secretKeyRef:
                      name:  armo-secret
                      key: account
                - name: ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name:  armo-secret
                      key: access-key

              restartPolicy: Never
          backoffLimit: 1
