kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mysql-scan
spec:
  metrics:
  - name: mysql-scan
    provider:
      job:
        spec:
          template:
            spec:
              serviceAccountName: kubescape-scan
              containers:
              - name: kubescape
                image: quay.io/kubescape/kubescape-cli:v3.0.4
                command:   ["sh -c false"]
                 # args:
                 #  - false
              # script:
              #   image: quay.io/kubescape/kubescape-cli:v3.0.4
              #   command: [ sh ]
              #   source: |
              #     ps
              #     ls /bin/*sh || true
              #     ls /usr/local/bin/*sh || true
              #     find / -name bash || true
              #     kubescape scan  workload --severity-threshold=low --namespace=mysql Rollout/mysql-rollout
              #     echo "Exit code $?"

                # - name: ACCOUNT
                #   valueFrom:
                #     secretKeyRef:
                #       name:  armo-secret
                #       key: account
                # - name: ACCESS_KEY
                #   valueFrom:
                #     secretKeyRef:
                #       name:  armo-secret
                #       key: access-key

              restartPolicy: Never
          backoffLimit: 1
