kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: rollout-scan
spec:
  metrics:
  - name: scan
    provider:
      job:
        spec:
          template:
            spec:
              serviceAccountName: kubescape-scan
              initContainers:
              - name: kubectl
                image: docker.io/bitnami/kubectl:latest
                command: ["/bin/sh", "-c"]
                args:
                - kubectl get deploy -n default nginx -o yaml > /data/workload.yaml
                volumeMounts:
                - name: shared-data
                  mountPath: /data
              containers:
              - name: kubescape
                image: quay.io/matthiasb_1/kubescape:latest
                command: ["/busybox/sh", -c]
                args:
                - kubescape scan --severity-threshold low /data/workload.yaml
                volumeMounts:
                - name: shared-data
                  mountPath: /data
                env:
                  - name: VERBOSE
                    value: "on"
                  - name: FRAMEWORKS
                    value: MITRE
                  # - name: ACCOUNT
                  #   valueFrom:
                  #     secretKeyRef:
                  #       name:  armo-secret
                  #       key: account
                  # - name: ACCESS_KEY
                  #   valueFrom:
                  #     secretKeyRef:
                  #       name:  armo-secret
                  #       key: access-key

              restartPolicy: Never
              volumes:
              - name: shared-data
                emptyDir: {}
          backoffLimit: 1
