apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mysql-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: your_password_here
  strategy:
    canary:
      stableService: mysql-active
      canaryService: mysql-preview
      steps:
      - setWeight: 50
      - pause: {}
      - analysis:
          templates:
          - templateName: scan
      - setWeight: 80
      - pause: {duration: 10s}      
