apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mysql-rollout
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.5
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: your_password_here
  strategy:
    canary:
      stableService: mysql
      canaryService: mysql-preview
      steps:
      - setWeight: 30
      - pause: {duration: 10s}
      - analysis:
          templates:
          - templateName: rollout-scan
      - setWeight: 80
      - pause: {duration: 10s}
