kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nginx-scan
spec:
  metrics:
  - name: nginx-scan
    provider:
      job:
        spec:
          # successfulJobsHistoryLimit: 1
          # failedJobsHistoryLimit: 1
          ttlSecondsAfterFinished: 86400
          template:
            spec:
              serviceAccountName: kubescape-scan
              containers:
                - name: kubescape
                  image: quay.io/kubescape/kubescape-cli:v3.0.4
                  command: ["kubescape"]
                  args:
                  - scan
                  - workload
                  - --severity-threshold=low
                  - --namespace=nginx-ks
                  - Rollout/nginx
                  env:
                    - name: VERBOSE
                      value: "on"
                    - name: FRAMEWORKS
                      value: MITRE
              restartPolicy: Never
          backoffLimit: 1
